version: '3.8'
services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - C:\Users\Lenovo\farm-platform\web\dist:/usr/share/nginx/html

  backend:
    image: python:3.10-slim
    ports:
      - "8000:8000"
    volumes:
      - C:\Users\Lenovo\farm-platform\backend:/app
    working_dir: /app
    command: >
      sh -c "pip install --root-user-action=ignore -r requirements.txt &&
      uvicorn main:app --reload --host 0.0.0.0 --port 8000"